const exec = require("executive");
const Client = require("node-rest-client").Client;

/**
 * @module owdit
 */

/**
 * @typedef VulnerabilityReport
 * @property {!String} title - Title of the vulnerability
 * @property {!String} description - Short description of the vulnerability
 * @property {!String} versions - Versions of the package that are affected by this vulnerability
 * @property {!String[]} references - A list of URLs containing links to more details about the vulnerability
 */

/**
 * @typedef VulnerablePackage
 * @property {!String} name - Name of the package
 * @property {!String} version - Version of the package in semver format
 * @property {!String[]} path - Top-bottom include list of the package; e.g. ["mypackage@1.0.2", "express@2.5.11", "qs@0.4.2"]
 * @property {!Vulnerability[]} vulnerabilities - List of found vulnerabilities for the package
 */

/**
 * @typedef DependencyReport
 * @property {!Number} vulnerabilityCount - Number of vulnerabilities in the report; can be zero
 * @property {VulnerablePackage[]} vulnerablePackages - A list of vulnerable packages together with their vulnerabilities
 */

/**
 * @callback CheckCallback
 * @param {?Error} error - Not null if an error occurred
 * @param {?DependencyReport} dependencyReport - Not null if no error occurred; contains the found vulnerabilities
 */

/**
 * Recursively checks the dependencies described in the package.json file in the directory `cwd`
 * for known vulnerabilities.
 * @param  {!String}   cwd            - The current working directory; used to locate the package.json file
 * @param  {!CheckCallback} callback  - Called when the function finishes
 * @returns {null}
 */
function check(cwd, callback) {
  const result = exec.sync("npm ls --production=true --json", {
    cwd:    cwd,
    strict: true,
    quiet:  true
  });

  if (result.status !== 0) {  //eslint-disable-line no-magic-numbers
    return callback(new Error(`Error running npm ls: ${result.stderr}`));
  }
  let packages = [];

  try {
    packages = JSON.parse(result.stdout);
  } catch (err) {
    return callback(err);
  }

  const registerModules = {};

  /**
   * Makes a flat list of the hierarchical dependency tree generated by npm ls.
   * This method also filters out double packages if there should be any present
   * @param  {String} parentPackage - name of the parent package
   * @param  {Object} dependencies  - Object containing nested key-value pairs for dependencies
   * @return {Object[]} A flat list of packages containing the package manager (i.e. npm), the name of the package and the version of the package
   * @private
   */
  function flattenDependencies(parentPackage, dependencies) {
    const list = [];
    const deps = Object.keys(dependencies);

    deps.forEach((dependency) => {
      const dependent = dependencies[dependency];
      const key = dependency + dependent.version;

      if (!registerModules.hasOwnProperty(key)) {
        const path = [...parentPackage, `${dependency}@${dependent.version}`];

        registerModules[key] = dependent;
        registerModules[key].path = path;
        list.push({
          pm:      "npm",
          name:    dependency,
          version: dependent.version
        });
        if (dependent.dependencies) {
          list.push(...flattenDependencies(path, dependent.dependencies));
        }
      }
    });

    return list;
  }
  if (packages.dependencies) {
    const client = new Client();
    const flatList = flattenDependencies([`${packages.name}@${packages.version}`], packages.dependencies);
    const restOptions = {
      data:    flatList,
      headers: {"Content-Type": "application/json"}
    };
    const request = client.post("https://ossindex.net/v2.0/package", restOptions, (data) => {
      let numVulnerabilities = 0;  //eslint-disable-line no-magic-numbers
      const vulnerablePackages = data.filter((element) => {
        numVulnerabilities += element["vulnerability-matches"];

        return element["vulnerability-matches"] > 0;  //eslint-disable-line no-magic-numbers
      }).map((element) => {
        return {
          name:            element.name,
          version:         element.version,
          path:            registerModules[`${element.name}${element.version}`].path,
          vulnerabilities: element.vulnerabilities.map((element) => {
            return {
              title:       element.title,
              description: element.description,
              versions:    element.versions,
              references:  element.references
            };
          })
        };
      });
      const vulnerabilityReport = {
        vulnerabilityCount: numVulnerabilities,
        vulnerablePackages: vulnerablePackages
      };

      return callback(null, vulnerabilityReport);
    });

    return request.on("error", callback);
  } else {
    return callback(null, {
      vulnerabilityCount: 0,  //eslint-disable-line no-magic-numbers
      vulnerablePackages: []
    });
  }
}

module.exports.check = check;
